enableBounceBlueWitherSkull = true
enableMoreInertialBlueWitherSkull = true
enableShootMoreBlueWitherSkull = true
enableSpinAndWhiteSummon = true
enableExplodeByHalfHealth = true
enableExplodeByDie = true
enableChargeAttack = true
enableDoubleHealth = false
enableMaintainWeakenedState = true
