name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1243399d7a8a9cc79bf48bb60cb4e0329f434768ce02b25e1e90791d5066694f"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
