name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a28a08ba712c3ac48a30cde004114384e771ce04e72dd4043b297b1cf70e7e10"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/openloader/data"
