name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b48924ab6ed0fc0a3ed1d284b439175daf3d2fd6c979a0f1336ff571a84517b3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
