name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df67e35af345a7c39ab86581ab94429b8bfe5db66088dd996f346943b471325"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
