name = "Rural Ambitions"
author = "ultratoon"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ad32e90e30889b7a8529d91a67ade625b0fd3c143c4c2bd24a1ba0617d30fd8"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
