name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c51caf2a2c66a176b489c3a4e24718b6489929b40aad90ae6e598c25a36b58c"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
