name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "558c684e8c265f771bdbe6d45fe97d69ceed93a1b7fc845db5a1f3a8494448b7"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
