name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "561f04237cbccb4e8da663e443e612d74cc68efed5ca76de5875e978ef063ee6"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
