name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9320a9aa60d7ec985cb04ab2f0972621cde07a528430d6bf604315e18674f62"

[versions]
fabric = "0.15.2"
minecraft = "1.20.1"
