name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bcec10a0a911c443d81e817bcaeebef8655532320e3a13e6a517b4438a620a1"

[versions]
fabric = "0.15.2"
minecraft = "1.20.1"
