name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c6c25337ce0ed49f67682b7daf9a70be0edfd59ef6ff0cdf6f300875a1a1f9"

[versions]
fabric = "0.15.2"
minecraft = "1.20.1"
