name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e064e2581f881ce769c023398ef3eb505a695d3401de54fd0e910732740aaad8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "resourcepacks/required_data"
