name = "Create Craft: Industrial New Age"
author = "UltraToon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0548aed73e979ede685a3032c87ae0b657bd2cda795cc5e318b15bc16a6b9c49"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
