name = "Create Craft: Industrial New Age"
author = "UltraToon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48eab87f3d3dc176b94c021f63e62ec628f3051db2bad4b9db2a4c6f64e4742a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
