name = "Minecraft: Chronicles"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f8dc56d20392d9376e11299337d8ad658da38b31f715dcbdc46764e4e1d2d00"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.2"
