name = "Minecraft: Chronicles"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7775b717f10e23c6c871f40e90e5768902f57d5106b2acefc958dd59d98e92"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.2"
