name = "Minecraft: Chronicles"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4f0171085d456ef72ac6f28fffda2dea1b19183963b08c9a8bab6c2ec2f6cf8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.2"
