name = "Minecraft Merged"
author = "ultratoon"
version = "1.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c01bd010ada59220e72d4d5e1a362c37c556a9af8b28238d9c10aaa4a1f5360f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1-pre9"
