name = "Minecraft Merged"
author = "ultratoon"
version = "1.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64a6f82d460b6ca64ec7097758f6a394e467e5ef423d4e381a99c4002848099a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.0.2"
