name = "Minecraft: Chronicles"
author = "ultratoon"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afb5facd3de0ec971d64ee0526bc2b8189b8c2948b901412dfb84520e14cc31a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.2"
