name = "Minecraft: Chronicles"
author = "ultratoon"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d38beb482f7567e9d4c21b5b66c4eb7eb00a45c670074573d8b564aec1a37cd"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.2"
