name = "Minecraft: Chronicles"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "606e582e5dd4fbfc6b3eabf1be16842b6a64b3e6101747f2451862a76b6787b3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.2"
