name = "Minecraft: Chronicles"
author = "ultratoon"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "667daafad16c73dae132726e7044f0a2b5f4a47cffe434ac5ee9c6b91a86bd5f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.2"
