[flavor_groups.distanthorizons]
name = "Distant Horizons"
id = "distanthorizons"
description = "[WIP] Distant Horizons toggle, turn off if you have low specs or want to avoid experiments, otherwise it can be on."
side = "both"
choices = ["distanthorizons_off", "distanthorizons_on"]

[flavor_groups.oculus]
name = "Shader Support (Oculus)"
id = "oculus"
description = "Shader support, turn off if you have low specs (or no shadders toggled ingame, but not as efficient), otherwise recommended to be on."
side = "client"
choices = ["oculus_off", "oculus_on"]

#[metafile.distanthorizons]
#flavors = ["distanthorizons_off", "distanthorizons_on"]
#[metafile.oculus]
#flavors = ["oculus_off", "oculus_on"]

