[flavor_groups.distanthorizons]
name = "Distant Horizons"
id = "distanthorizons"
description = "[WIP] Distant Horizons toggle, turn off if you have low specs or want to avoid experiments, otherwise it can be on."
side = "both"
choices = ["distanthorizons_off", "distanthorizons_on"]

[flavor_groups.oculus]
name = "Shader Support (Oculus)"
id = "oculus"
description = "Shader support, turn off if you have low specs (or no shadders toggled ingame, but not as efficient), otherwise recommended to be on."
side = "client"
choices = ["oculus_off", "oculus_on"]

[flavor_groups.immersiveportals]
name = "Immersive Portals"
id = "immersiveportals"
description = "Immersive Portals support, it preloads chunks through portals that you can view (check page if confused). Affects chunk performance, recommended to be on."
choices = ["immersiveportals_off", "immersiveportals_on"]

[metafile.distanthorizons]
flavors = ["distanthorizons_off", "distanthorizons_on"]
[metafile.oculus]
flavors = ["oculus_off", "oculus_on"]
[metafile.immersive-portals-for-forge]
flavors = ["immersiveportals_off", "immersiveportals_on"]

