name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63e6f28b5882b73e5d1e1b1139fd8c6cc71605110e9d075cf3967d0ccf1db489"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
