name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53904dc3f643a0ba076ae7216d242ececb12416f99793c208b18b1a0dfacba61"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
