name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544cae8433742bd20ab7b5f9135804bcc58195e8fe8ab0bbb11edfcc0218f372"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
