name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "907aa272486cc9b9d47909889e052961f90fcf8d5ece0c830ca920961306b0ef"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
