name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17615d7f63a5d958f83c93051024543e4231b090cd80b77b145260597e1a80f8"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
