name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "505d3b6153087b091e0a9901210ed99433391a8185b08f8b2439323e1b3b4e09"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
