name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69f94f46fde019c6eb5c872dd71a068322d1409921b912131585a12dcb2ebd08"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
