name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b14d3ba01d332e14e93a40eefe7357f2a47eaf43187202db82fbfa59cd6d9aa3"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
