name = "Rural Ambitions"
author = "ultratoon"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "812e018df344335f4794de6708113805a37b73c2ec9c456c024dae1e0fbfc9ea"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
