name = "Rural Ambitions"
author = "ultratoon"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6089e47e3989a96026e02c20e89eef36c3dc9f1e614c1149b4a5a2573eca552f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
