name = "Rural Ambitions"
author = "ultratoon"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce06df8d9b0ccd84f22cc62206d4c439977e82055c41f4a79850f62cc5d88b19"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
