name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "139ca7a4d53af9ba309d62f359a8a3adeb26c9bc9f38abb0c679b70908340016"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
