name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32bef05067b837580ccaa91918a70d33564f9069b10f2bcf75ae7e7a495609af"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
