name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa855f5ca495fe414ef939814f330fb0131d655e1ba115e7eabde1e6dc6f1436"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
