name = "Rural Ambitions"
author = "ultratoon"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d6b5423e448f7ffaa9b03a9783e123bab9faf421f29f69a1bdfcdcd8d5bf1dc"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
