name = "Rural Ambitions"
author = "ultratoon"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0121050fbd14410cfa2e7d4fdc313c293c110599c3e236d610d41db77b7f96c6"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
