name = "Rural Ambitions"
author = "ultratoon"
version = "2.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d02327d93e28f4a47a37780f5ece0de5e060666ad2c4897602379a0f8028e454"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
