[sleeping]
playerSnoreChance = 0
villagerSnoreChance = 0.3
villagerSnoreSoundVolume = 0.3

[humanoids.player]
stomachGrowlingThreshold = 0
heartBeatingThreshold = 6
heartbeatVolume = 1.0
heartBeatingWaitTime = 3

[dustClouds]
scale = 2.0
alpha = 1.0
preventWhenRaining = true
flyIntoWall = true
lessViewBlocking = true
playerFell = true
mobFell = true
landMaceAttack = true
playerRunning = false
mobRunning = true
playerRunningRequiresSpeed = true
