name = "Create Craft"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81550fa0a3c8ea324b35a5b755cfbead65e13e2b54a18a8f15bd62204a9f9390"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
