name = "Create Craft"
author = "ultratoon"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d8a4bffdbdedcc7b7686f6c9515b1d9db5d8239ade821de4ebfeea8493058a2"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
