name = "Create Craft"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a64fa651d784df22c33fd0e80aede0ea4e68b12a2282079e62afcff0d7ba5cf"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
