name = "Create Craft"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "647799be3055521289c3db004ac82bf5d1185c95c68a433cf74927dfa74d1a5c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
