name = "Create Craft"
author = "ultratoon"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f62288b0cae84b5d897f601d7a5c4265790f5f8ee4bd07dd27325947227f4b5"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
