name = "Create Craft"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95fa616b2b78569470e86a4438b6846179e09973a612aad43a766b6563c42abf"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
