name = "Create Craft"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f886f83351f686759b5428089f7f8e9ed8c33a60f7d0a540576b3288eb36cce"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
