name = "Create Craft"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41de666b12b34e2cbd7d210e385e93470dffb1cf245934583f41024627eb8a70"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
