name = "Create Craft"
author = "ultratoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac2f590376fb3c8b23bc8788b82cef09f9dadefc31e4b1173e914ff1481a769f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
