name = "Create Aero"
author = "UltraToon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "628d47c5f6c1fcad337be2dd52682387d7eac0291a34f846d49dfe03c6ba96a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
