name = "Create Aero"
author = "UltraToon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88a89349e2b4d2b3deebd309c94cb10f722c686c47349a999782c806f3b55ca7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
