name = "Create Aero"
author = "UltraToon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c940cba7fc1193ddd04d569a1ce3e24fd43974bc9f12fd2f3448089bb79dba6c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
