name = "ParaPack Remastered"
author = "ultratoon [Ivan Blackburn]"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e1a12d33c78f7b9877bb97c738fa7f9913d06e932627808af1fb6e9854d4040"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
