name = "ParaPack Remastered"
author = "ultratoon [Ivan Blackburn]"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "798aab29c6b02c02af80f763a114bdf0aa0c5c41b4398d935206980af19ba05c"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
