name = "ParaPack Remastered"
author = "ultratoon [Ivan Blackburn]"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65da0c9cdcad399d85c60f0ebfe85b7d0fc34e2551091861ff6cd9430b464b3e"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
