name = "ParaPack Remastered"
author = "ultratoon [Ivan Blackburn]"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17545a15a5a656b28711fcaea37071ee72e70e73884bde7fe7c33ef7fdb74326"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
