name = "ParaPack Remastered"
author = "ultratoon [Ivan Blackburn]"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9809f189df46075e98e0155fa6ab41dad053705732c479b2e5aa245ed3f67baa"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
