#!/bin/bash
printf "Packwiz update? (y/n): "; read -r ans && [ "$ans" = y ] && packwiz update -a
packwiz refresh || true
git add . # stage all
git commit -a -m "[$(date +%T)] $(git diff --cached --name-only | paste -sd, -)"
git pull --rebase origin main || { echo "Merge conflict detected! Please resolve."; exit 1; }
git push origin main
