#Should we control the window. Disabling this disables new GL features and can be bad for mods that rely on them.
earlyWindowControl = false
#Early window starts maximized
earlyWindowMaximized = true
#Squir?
earlyWindowSquir = true

