[resourcepacks]
required = [
    "resourcepacks/required/modpack-resource",
    "resourcepacks/required/"
]

[datapacks]
required = [
    "resourcepacks/required/modpack-data",
    "resourcepacks/required/"
]
