[resourcepacks]
required = [
    "resourcepacks/required/modpack-resource",
    "resourcepacks/required/"
]

optional = [
    "resourcepacks/DetailedAnimationsReworked - V1.15.zip"
]

[datapacks]
required = [
    "resourcepacks/required/modpack-data",
    "resourcepacks/required/"
]
