[resourcepacks]
required = [
    #"other_folder/random_pack.zip" # You can also point at specific files!
    "resourcepacks/modpack-resource",
    "resourcepacks/"
]

optional = [
    "global_packs/optional_data/"
]

[datapacks]
required = [
    "resourcepacks/modpack-data",
    "resourcepacks/"
]
