
#Client options
[client]
	#Boss music
	[client.boss_music]
		#Toggles the Wither Storm boss theme. NOTE: this theme is from MC:SM and is subject to copyright.
		#Default: false
		playWitherStormTheme = true

