hash-format = "sha256"

[[files]]
file = "config/alexsmobs.toml"

[[files]]
file = "config/bettercombat/client.json5"

[[files]]
file = "config/bettercombat/fallback_compatibility.json"

[[files]]
file = "config/bettercombat/server.json5"

[[files]]
file = "config/chloride-client.json"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/emi.css"

[[files]]
file = "config/endrem.toml"

[[files]]
file = "config/global_data_and_resourcepacks.toml"

[[files]]
file = "config/mowziesmobs-common.toml"

[[files]]
file = "kubejs/assets/kubejs/textures/block/example_block.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/example_item.png"

[[files]]
file = "kubejs/client_scripts/example.js"

[[files]]
file = "kubejs/config/client.properties"

[[files]]
file = "kubejs/config/common.properties"

[[files]]
file = "kubejs/data/rootoffear/tags/worldgen/biome/wilted_spawns_in.json"

[[files]]
file = "kubejs/server_scripts/endremastered.js"

[[files]]
file = "kubejs/server_scripts/guidebook.js"

[[files]]
file = "kubejs/server_scripts/witherstorm.js"

[[files]]
file = "kubejs/startup_scripts/example.js"

[[files]]
file = "mods/advancement-plaques.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-mobs-extra-music.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-combat-by-daedelus.pw.toml"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
metafile = true

[[files]]
file = "mods/better-trees.pw.toml"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
metafile = true

[[files]]
file = "mods/chloride.pw.toml"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/crackers-wither-storm-mod.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
metafile = true

[[files]]
file = "mods/deltaboxlib.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/ender-trigon.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-boss-bars-mod.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-forge.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
metafile = true

[[files]]
file = "mods/globalpacks.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm-delight.pw.toml"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm.pw.toml"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
metafile = true

[[files]]
file = "mods/lukis-grand-capitals.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/more-advancements-mod-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/mowzies-cataclysm.pw.toml"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
metafile = true

[[files]]
file = "mods/nerb.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/pale-garden-backport.pw.toml"
metafile = true

[[files]]
file = "mods/pandalib.pw.toml"
metafile = true

[[files]]
file = "mods/pandas-falling-trees.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
metafile = true

[[files]]
file = "mods/rediscovered.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
metafile = true

[[files]]
file = "mods/sounds-of-the-forest.pw.toml"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/the-masquerade-(illager-boss).pw.toml"
metafile = true

[[files]]
file = "mods/the-root-of-fear.pw.toml"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
metafile = true

[[files]]
file = "mods/true-ending.pw.toml"
metafile = true

[[files]]
file = "mods/via-romana.pw.toml"
metafile = true

[[files]]
file = "mods/wither-spawn-animation.pw.toml"
metafile = true

[[files]]
file = "mods/wither-storm-combat.pw.toml"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
metafile = true

[[files]]
file = "patchouli_books/modpack_info/book.json"

[[files]]
file = "patchouli_books/modpack_info/en_us/categories/lore_catgory.json"

[[files]]
file = "patchouli_books/modpack_info/en_us/entries/lore/lore_entry.json"

[[files]]
file = "resourcepacks/blinking-ender-eyes.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/music-and-melody.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/overlays.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/vn4s-fresh-wither-storm.pw.toml"
metafile = true
