name: Update unsup.jar

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download latest unsup.jar
        run: |
          curl -L $(curl -s https://git.sleeping.town/api/v1/repos/unascribed/unsup/releases/latest | jq -r '.assets[] | select(.name | endswith(".jar")) | .browser_download_url') -o Minecraft_Chronicles/unsup.jar
      
      - name: Commit if changed
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Minecraft_Chronicles/unsup.jar
          git commit -m "Update unsup.jar" || echo "No changes to commit for unsup.jar"
          git push
